package arcgt

const BAD_REQUEST = "BAD_REQUEST"
const BAD_GATEWAY = "BAD_GATEWAY"
const TOKEN = "TOKEN"
const EMAIL_NOT_VERIFY = "EMAIL_NOT_VERIFY"

const REGISTER_PASSWORD_REQUIRED = "REGISTER_PASSWORD_REQUIRED"
const REGISTER_PASSWORD_CHARACTERS = "REGISTER_PASSWORD_CHARACTERS"
const REGISTER_PASSWORD_SPECIAL_CHARACTERS = "REGISTER_PASSWORD_SPECIAL_CHARACTERS"

const REGISTER_FIRST_NAME_REQUIRED = "REGISTER_FIRST_NAME_REQUIRED"
const REGISTER_FIRST_NAME_CHARACTERS = "REGISTER_FIRST_NAME_CHARACTERS"

const REGISTER_LAST_NAME_REQUIRED = "REGISTER_LAST_NAME_REQUIRED"
const REGISTER_LAST_NAME_CHARACTERS = "REGISTER_LAST_NAME_CHARACTERS"

const REGISTER_SHOP_NAME_REQUIRED = "REGISTER_SHOP_NAME_REQUIRED"
const REGISTER_SHOP_NAME_CHARACTERS = "REGISTER_SHOP_NAME_CHARACTERS"

const REGISTER_EMAIL_REQUIRED = "REGISTER_EMAIL_REQUIRED"
const REGISTER_EMAIL_INVALID_EMAIL = "REGISTER_EMAIL_INVALID_EMAIL"
const REGISTER_EMAIL_ALREADY_EXISTS = "REGISTER_EMAIL_ALREADY_EXISTS"

const LOGIN_ACCOUNT_PASSWORD_REQUIRED = "LOGIN_ACCOUNT_PASSWORD_REQUIRED"
const LOGIN_ACCOUNT_PASSWORD_ERROR = "LOGIN_ACCOUNT_PASSWORD_ERROR"

const CHANGE_OLD_PASSWORD_REQUIRED = "CHANGE_OLD_PASSWORD_REQUIRED"
const CHANGE_OLD_PASSWORD_ERROR = "CHANGE_OLD_PASSWORD_ERROR"
const CHANGE_NEW_PASSWORD_REQUIRED = "CHANGE_NEW_PASSWORD_REQUIRED"
const CHANGE_NEW_PASSWORD_CHARACTERS = "CHANGE_NEW_PASSWORD_CHARACTERS"
const CHANGE_NEW_PASSWORD_SPECIAL_CHARACTERS = "CHANGE_NEW_PASSWORD_SPECIAL_CHARACTERS"

const LOGIN_ACCOUNT_SPAM_LOGIN_ERROR = "LOGIN_ACCOUNT_SPAM_LOGIN_ERROR"
const VERIFY_CODE_ERROR = "VERIFY_CODE_ERROR"
const VERIFY_CODE_TIMEOUT_ERROR = "VERIFY_CODE_TIMEOUT_ERROR"
const EMAIL_PREVIOUSLY_VERIFIED_ERROR = "EMAIL_PREVIOUSLY_VERIFIED_ERROR"
const VERIFY_EMAIL_NOT_SEND_BY_NOW_ERROR = "VERIFY_EMAIL_NOT_SEND_BY_NOW_ERROR"

const VERIFY_CODE_REQUIRED = "VERIFY_CODE_REQUIRED"
const ROLE_VERIFY_CODE_REQUIRED = "ROLE_VERIFY_CODE_REQUIRED"
const ROLE_VERIFY_CODE_ERROR = "ROLE_VERIFY_CODE_ERROR"

// const VERIFY_CODE_CHARACTERS = "VERIFY_CODE_CHARACTERS"
const RESET_PASSWORD_TIMEOUT_ERROR = "RESET_PASSWORD_TIMEOUT_ERROR"
const RESET_PASSWORD_KEY_PREVIOUSLY_USED_ERROR = "RESET_PASSWORD_KEY_PREVIOUSLY_USED_ERROR"
const RESET_PASSWORD_SPAM_RESET_PASSWORD_ERROR = "RESET_PASSWORD_SPAM_RESET_PASSWORD_ERROR"

const SHOP_ID_NOT_FOUND = "SHOP_ID_NOT_FOUND"

const STORE_COUNTRY_REQUIRED = "STORE_COUNTRY_REQUIRED"
const STORE_POSTAL_REQUIRED = "STORE_POSTAL_REQUIRED"
const STORE_CITY_REQUIRED = "STORE_CITY_REQUIRED"
const STORE_ADDRESS_REQUIRED = "STORE_ADDRESS_REQUIRED"
const STORE_DOMAIN_PREFIX_CHARACTERS = "STORE_DOMAIN_PREFIX_CHARACTERS"
const STORE_DOMAIN_PREFIX_REQUIRED = "STORE_DOMAIN_PREFIX_REQUIRED"
const STORE_NAME_CHARACTERS = "STORE_NAME_CHARACTERS"
const STORE_NAME_REQUIRED = "STORE_NAME_REQUIRED"

const STORE_DOMAIN_PREFIX_ALREADY_EXISTS = "STORE_DOMAIN_PREFIX_ALREADY_EXISTS"
const STORE_STATUS_DELETE_BY_SUPPORT = "STORE_STATUS_DELETE_BY_SUPPORT"

const ROLE_ID_REQUIRED = "ROLE_ID_REQUIRED"
const ROLE_ID_NOT_FOUND = "ROLE_ID_NOT_FOUND"
const ROLE_ID_PREVIOUSLY_VERIFIED_ERROR = "ROLE_ID_PREVIOUSLY_VERIFIED_ERROR"
const ROLE_ID_NOT_SEND_BY_NOW_ERROR = "ROLE_ID_NOT_SEND_BY_NOW_ERROR"

const ROLE_EMAIL_REQUIRED = "ROLE_EMAIL_REQUIRED"

const THEME_ID_NOT_FOUND = "THEME_ID_NOT_FOUND"
const MY_THEME_ID_NOT_FOUND = "MY_THEME_ID_NOT_FOUND"
